apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api-demo
  labels:
    app: springboot-api-demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: springboot-api-demo
  template:
    metadata:
      labels:
        app: springboot-api-demo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: springboot-api-demo
        image: 192.168.1.168:5000/springboot-api-demo:latest
        ports:
        - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-api-demo
spec:
  type: ClusterIP
  selector:
    app: springboot-api-demo
  ports:
  - name: springboot-api-demo
    protocol: TCP
    port: 8080
    targetPort: 8080
